export const PRODUCTS = [
  {
    id: 1,
    title: "Rustic Concrete Soap",
    price: "12.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/nightlife",
    description:
      "Repudiandae in omnis molestiae iure et vitae aliquid. Dolore nisi et quia nobis sit ea dolorem repudiandae. Ut atque veritatis quia dolores ipsa. Ut et dolores aut sapiente delectus culpa excepturi et. Ut aut sed.",
    category: "Music",
    counter:1,
  },
  {
    id: 2,
    title: "Unbranded Wooden Computer",
    price: "538.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/food",
    description:
      "Voluptatem iste dolore molestiae fuga. Qui aut nihil facilis fuga nihil. Amet in sint voluptas iusto itaque.",
    category: "Music",
    counter:1,
  },
  {
    id: 3,
    title: "Generic Frozen Tuna",
    price: "26.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/food",
    description:
      "Facilis aut veniam ipsa qui deserunt officiis et qui. Rerum voluptatum qui voluptas. Illo sit in numquam voluptatem minima saepe odit voluptas. Totam enim vitae dignissimos non rerum. Repellendus eos quia ut.",
    category: "Sports",
    counter:1,
  },
  {
    id: 4,
    title: "Handcrafted Frozen Ball",
    price: "609.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Quod ab et culpa rerum vel repellat occaecati et id. Facere fugit beatae. Magni quos voluptatibus labore ipsum similique sit temporibus.",
    category: "Computers",
    counter:1,
  },
  {
    id: 5,
    title: "Licensed Concrete Chicken",
    price: "70.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/business",
    description:
      "Ab ab voluptates sed dolor deleniti temporibus impedit omnis. Facere qui saepe. Voluptatibus in omnis ut illo eius modi voluptatem.",
    category: "Garden",
    counter:1,
  },
  {
    id: 6,
    title: "Generic Plastic Hat",
    price: "590.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/business",
    description:
      "Possimus et veritatis temporibus nihil. Labore iusto dolores. Voluptas dicta vel eum iste provident quis ullam et. Nisi omnis inventore quis odit dolore assumenda cum autem. Exercitationem sint aliquam. Doloremque dolores animi cupiditate ut.",
    category: "Industrial",
    counter:1,
  },
  {
    id: 7,
    title: "Fantastic Wooden Chips",
    price: "406.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/business",
    description:
      "Sed harum saepe quis laborum enim ut et. Nobis nostrum natus ea quisquam temporibus. Distinctio delectus ut omnis ullam amet. Quas maiores minus natus quos.",
    category: "Clothing",
    counter:1,
  },
  {
    id: 8,
    title: "Ergonomic Steel Gloves",
    price: "895.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Porro cupiditate quaerat incidunt sunt natus. Facilis amet quidem placeat voluptatem quas sit id impedit. Sunt ducimus in soluta commodi veritatis voluptatem. Eos quibusdam eaque fugiat sunt.",
    category: "Jewelery",
    counter:1,
  },
  {
    id: 9,
    title: "Sleek Wooden Shirt",
    price: "883.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/food",
    description:
      "Tempora facilis sed dolorum. Optio animi et voluptatum. Consequatur nihil aut saepe quia numquam.",
    category: "Industrial",
    counter:1,
  },
  {
    id: 10,
    title: "Awesome Plastic Shirt",
    price: "793.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/animals",
    description:
      "Soluta sequi excepturi autem ipsum illo est. Quia dignissimos ut similique eius quisquam. Et similique voluptatem modi voluptatem et. Dolorem perferendis distinctio culpa consequatur. Animi ratione veritatis quisquam consequatur magnam. Dignissimos numquam quia et optio et aliquid aspernatur.",
    category: "Automotive",
    counter:1,
  },
  {
    id: 11,
    title: "Handcrafted Frozen Pizza",
    price: "735.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/business",
    description:
      "Nostrum cupiditate ad. Sapiente voluptatem nihil est velit sit voluptas. Vel vero quia.",
    category: "Grocery",
    counter:1,
  },
  {
    id: 12,
    title: "Practical Fresh Bacon",
    price: "550.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/technics",
    description:
      "Beatae provident quo qui iste sed ut culpa sunt repellendus. Non saepe distinctio qui et et. Enim repellendus ut quaerat rerum modi nobis. Velit ex id ad. Saepe omnis nobis qui quis ipsum quas facere soluta. Voluptas omnis optio.",
    category: "Outdoors",
    counter:1,
  },
  {
    id: 13,
    title: "Practical Frozen Chicken",
    price: "489.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/sports",
    description:
      "Quaerat voluptate placeat earum et consequatur et tempore. Numquam rem et. Corrupti enim enim qui rem. Aut error vel sed vero.",
    category: "Music",
    counter:1,
  },
  {
    id: 14,
    title: "Generic Granite Car",
    price: "565.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/technics",
    description:
      "Vitae corporis saepe. Doloribus veniam possimus temporibus magnam fuga quia dolor. Rem nobis alias dolorem sed enim quis excepturi soluta eaque.",
    category: "Tools",
    counter:1,
  },
  {
    id: 15,
    title: "Small Plastic Soap",
    price: "515.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/people",
    description:
      "Dolores suscipit quia. Delectus aspernatur aut omnis dolores ullam eaque ea maxime. Et omnis ullam praesentium non quisquam enim molestias excepturi sed. Provident labore quisquam vitae aut necessitatibus adipisci et quidem. Doloremque ut ipsam.",
    category: "Industrial",
    counter:1,
  },
  {
    id: 16,
    title: "Fantastic Plastic Hat",
    price: "207.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/technics",
    description:
      "Deserunt aut consequuntur. Doloribus eos architecto ut dignissimos sed. Eius consectetur repellat dolores et. Sint aut dolore laboriosam blanditiis et corrupti repellat.",
    category: "Clothing",
    counter:1,
  },
  {
    id: 17,
    title: "Practical Cotton Chips",
    price: "930.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Est quam dolorum nihil quaerat qui est dolorum explicabo. Repudiandae nihil placeat autem omnis neque sint. In dignissimos aliquid animi reprehenderit voluptatum aspernatur est ratione dolores. Distinctio non natus at iusto et incidunt.",
    category: "Kids",
    counter:1,
  },
  {
    id: 18,
    title: "Handmade Wooden Pizza",
    price: "457.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/abstract",
    description:
      "Deserunt exercitationem facere quod. Vel iusto velit voluptas qui rerum mollitia. Quisquam tempore atque. Voluptas placeat autem provident dolores consequatur temporibus itaque occaecati. Ad itaque vel excepturi incidunt esse cum. Numquam cupiditate qui exercitationem nostrum quo autem.",
    category: "Books",
    counter:1,
  },
  {
    id: 19,
    title: "Tasty Concrete Shoes",
    price: "721.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/city",
    description:
      "Similique earum natus et. Officiis adipisci corrupti autem voluptatem quaerat aliquam rerum. Nihil atque qui deleniti aut veritatis saepe rerum. Animi magnam qui voluptatem inventore molestiae hic asperiores.",
    category: "Garden",
    counter:1,
  },
  {
    id: 20,
    title: "Awesome Plastic Computer",
    price: "112.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/technics",
    description:
      "Totam aut minus hic ut qui possimus atque. Est labore et vel fuga nihil est voluptate. Ullam fuga vero dolores.",
    category: "Beauty",
    counter:1,
  },
  {
    id: 21,
    title: "Small Fresh Cheese",
    price: "658.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/fashion",
    description:
      "Nobis perspiciatis assumenda maiores sed id. Non eum vero nobis. Facere non dignissimos. Voluptatem quae voluptatibus doloribus. Vitae modi saepe culpa dolore praesentium ipsam facere quaerat sint. Similique voluptatem eos esse sit sed doloremque eligendi dolores aut.",
    category: "Toys",
    counter:1,
  },
  {
    id: 22,
    title: "Handmade Granite Keyboard",
    price: "213.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Dolorem suscipit cum error est. Quod et dicta perferendis perferendis est totam cum quis ut. Eos provident id blanditiis quo beatae repellat. Atque qui nihil reprehenderit dolore.",
    category: "Beauty",
    counter:1,
  },
  {
    id: 23,
    title: "Generic Plastic Ball",
    price: "734.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/city",
    description:
      "Velit corporis dolorum aut provident omnis voluptate. Quaerat accusamus vel tenetur sint tenetur libero. Reiciendis nobis quae. Omnis assumenda possimus accusantium facilis temporibus saepe maiores. Et vel quam rem neque.",
    category: "Computers",
    counter:1,
  },
  {
    id: 24,
    title: "Gorgeous Metal Towels",
    price: "420.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Unde consequatur fugit et ut eum beatae. Aspernatur dolor omnis odio est ducimus totam libero. Nihil possimus harum voluptate laudantium ex reiciendis nihil. Asperiores itaque dicta eveniet accusantium soluta. Consequatur quis dolorem eaque ex. Dolores deleniti consequuntur placeat.",
    category: "Kids",
    counter:1,
  },
  {
    id: 25,
    title: "Incredible Metal Gloves",
    price: "775.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/food",
    description:
      "Quis voluptas earum praesentium eligendi et tempora. Nihil nihil quo accusamus dolor minus. Id voluptatem est nihil tenetur sed officia et. Pariatur saepe animi iure fuga sunt qui. Error magnam numquam nisi eaque nesciunt culpa. Rerum tempora quibusdam.",
    category: "Baby",
    counter:1,
  },
  {
    id: 26,
    title: "Ergonomic Plastic Salad",
    price: "710.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/transport",
    description:
      "Voluptas qui illo velit. Vero in laboriosam. Porro odio voluptatem sapiente omnis architecto veniam praesentium ipsum sed.",
    category: "Health",
    counter:1,
  },
  {
    id: 27,
    title: "Gorgeous Metal Mouse",
    price: "799.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/food",
    description:
      "Sed voluptates consequuntur ea voluptas et unde. Atque id voluptate voluptates ipsa. A voluptatem dicta. Doloremque eligendi quidem dignissimos reiciendis corrupti aut praesentium in. Quos et cumque quia odio qui quis.",
    category: "Music",
    counter:1,
  },
  {
    id: 28,
    title: "Practical Rubber Sausages",
    price: "913.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/animals",
    description:
      "Delectus et velit. Eius tenetur provident voluptas vero animi laboriosam blanditiis. Sed quibusdam eligendi dolor quia enim unde labore. A adipisci ut qui non tempora non. Modi delectus iste incidunt est. Facere et asperiores consequatur pariatur molestiae.",
    category: "Home",
    counter:1,
  },
  {
    id: 29,
    title: "Ergonomic Granite Hat",
    price: "470.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/abstract",
    description:
      "Porro quis qui eos est itaque ut. Sint ut expedita fugiat. Consequuntur iste dolor non omnis corrupti est.",
    category: "Shoes",
    counter:1,
  },
  {
    id: 30,
    title: "Rustic Metal Chicken",
    price: "603.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/business",
    description:
      "Quos reprehenderit ut voluptas nulla. Pariatur quia nulla doloribus exercitationem omnis recusandae voluptates. Totam beatae magnam qui et voluptatum ut. Molestias in tempora id. Suscipit quia minima doloribus qui perferendis et animi dolor. Doloribus provident distinctio.",
    category: "Games",
    counter:1,
  },
  {
    id: 31,
    title: "Fantastic Rubber Soap",
    price: "206.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Iste nesciunt ipsa repellendus perspiciatis iusto. Odio qui aspernatur ullam. Deleniti facere sit impedit nisi accusamus eos enim inventore. Adipisci eos corporis inventore repellendus. Est ipsum molestias corporis ut exercitationem magnam. Quia necessitatibus porro debitis mollitia laborum impedit facilis id deserunt.",
    category: "Baby",
    counter:1,
  },
  {
    id: 32,
    title: "Rustic Soft Keyboard",
    price: "16.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/people",
    description:
      "Voluptatibus nobis aut amet fugiat ut vero illo. Minima totam minima voluptate eligendi. Ut repudiandae sed vitae neque reprehenderit. Sunt consequatur commodi. Eveniet inventore ipsam et quos sed eos quis. Eum animi iure ut possimus in ex.",
    category: "Outdoors",
    counter:1,
  },
  {
    id: 33,
    title: "Sleek Steel Hat",
    price: "500.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/technics",
    description:
      "Qui hic molestiae laborum tempore aut labore magni. Odit fugiat sunt. Facere eos dolorem atque repellendus eos.",
    category: "Health",
    counter:1,
  },
  {
    id: 34,
    title: "Sleek Fresh Keyboard",
    price: "194.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/sports",
    description:
      "Molestias repellat magnam quos iure eos et eos velit nam. Et vel optio porro alias est deserunt totam eum. Et voluptatem optio voluptas consequatur harum dolores.",
    category: "Industrial",
    counter:1,
  },
  {
    id: 35,
    title: "Small Fresh Ball",
    price: "401.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/fashion",
    description:
      "Quia consequatur occaecati suscipit ipsam temporibus vel quas non. Iste fugit hic ut nobis quo enim omnis. Vero inventore soluta id ab eos quia impedit minus. Aut iste repellat voluptatem quo similique porro nesciunt sint et.",
    category: "Baby",
    counter:1,
  },
  {
    id: 36,
    title: "Sleek Plastic Shoes",
    price: "294.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/fashion",
    description:
      "Adipisci qui est repudiandae et. Omnis consequatur qui dignissimos ea rerum. Aliquam tempore eaque numquam nam nisi ratione. Sapiente architecto rerum quisquam laboriosam earum nostrum sunt. Et earum eum et non quo quis labore eligendi.",
    category: "Outdoors",
    counter:1,
  },
  {
    id: 37,
    title: "Unbranded Rubber Chair",
    price: "858.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/nature",
    description:
      "Voluptatem odit provident et. Ab dicta cum quis veniam consequatur repellat. Aut possimus ut recusandae ipsa quis voluptates dolorem quae at. Recusandae ab perferendis vero in et. Qui rem repellat aliquam aperiam.",
    category: "Automotive",
    counter:1,
  },
  {
    id: 38,
    title: "Incredible Concrete Mouse",
    price: "567.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Ad eos perspiciatis ipsa. Autem nisi itaque dolore necessitatibus. Voluptas molestias alias provident dolorum. Corporis voluptatem labore id eaque.",
    category: "Tools",
    counter:1,
  },
  {
    id: 39,
    title: "Intelligent Soft Pants",
    price: "799.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/business",
    description:
      "Sunt exercitationem ipsum labore ut aspernatur. Sit et architecto quidem ratione optio. Sint quidem corporis magni. Dolores maxime sit voluptatem quo quis voluptates enim cum quis. Dicta commodi quas. Et totam accusamus eaque.",
    category: "Shoes",
    counter:1,
  },
  {
    id: 40,
    title: "Incredible Rubber Salad",
    price: "36.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/sports",
    description:
      "Quia omnis nam quaerat soluta quod est facere. Dolorum commodi ut placeat corrupti quis cupiditate veritatis eum. Quo ut laborum nemo culpa. Impedit beatae est.",
    category: "Baby",
    counter:1,
  },
  {
    id: 41,
    title: "Sleek Granite Towels",
    price: "513.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/fashion",
    description:
      "Voluptatem sint ea quasi consequatur ipsa sit harum. Deleniti aspernatur aut impedit officia ullam laboriosam et architecto autem. Vero nulla voluptas est culpa. Rerum nulla velit molestias necessitatibus culpa qui.",
    category: "Home",
    counter:1,
  },
  {
    id: 42,
    title: "Handmade Frozen Table",
    price: "320.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/technics",
    description:
      "Est accusantium vero vel enim. Dicta veritatis velit. Mollitia nemo consequatur. Et neque qui dolorum et expedita qui cupiditate. Rerum molestiae veniam nesciunt. Molestias eligendi ipsa enim occaecati tempore suscipit corporis neque aspernatur.",
    category: "Books",
    counter:1,
  },
  {
    id: 43,
    title: "Tasty Steel Fish",
    price: "598.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/city",
    description:
      "Voluptatem et voluptas omnis voluptatem minus. Aspernatur et maxime sunt magnam laborum iste id voluptatum. Quia neque recusandae in sapiente id id autem repellendus officiis. Vitae minima explicabo qui nisi eligendi.",
    category: "Jewelery",
    counter:1,
  },
  {
    id: 44,
    title: "Sleek Fresh Tuna",
    price: "435.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/nightlife",
    description:
      "Aspernatur ut quos itaque tempora. Itaque nulla est. Dolor quis non iste consequatur voluptatum quia.",
    category: "Beauty",
    counter:1,
  },
  {
    id: 45,
    title: "Small Fresh Tuna",
    price: "626.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/people",
    description:
      "Dignissimos officiis repellat vel numquam libero dolorum saepe minus. Rerum ullam dicta maiores quos magni corrupti dolorem est qui. Temporibus voluptatem amet ipsam asperiores sint dicta. Ab qui aliquid. Doloremque exercitationem excepturi consequatur beatae.",
    category: "Grocery",
    counter:1,
  },
  {
    id: 46,
    title: "Unbranded Steel Pants",
    price: "520.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/technics",
    description:
      "Vitae voluptatem hic occaecati dolore doloremque occaecati laboriosam adipisci. Repellendus vel suscipit saepe eveniet nisi. Cumque placeat qui perferendis et voluptates qui provident reiciendis.",
    category: "Outdoors",
    counter:1,
  },
  {
    id: 47,
    title: "Intelligent Granite Shoes",
    price: "153.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/technics",
    description:
      "Eum deleniti ut odio. Error eius incidunt velit dignissimos aspernatur. Nulla a eum qui tenetur iure ea. Error mollitia dolores omnis. Labore consequuntur magnam rerum et ullam ducimus maxime sunt.",
    category: "Baby",
    counter:1,
  },
  {
    id: 48,
    title: "Tasty Concrete Hat",
    price: "268.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/city",
    description:
      "In animi qui reiciendis unde eos labore in cupiditate. Reiciendis et eos similique nihil vero. Est reiciendis dolores atque qui quis.",
    category: "Garden",
    counter:1,
  },
  {
    id: 49,
    title: "Unbranded Steel Hat",
    price: "71.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/transport",
    description:
      "Voluptatem aut quis sunt. Soluta blanditiis sint dicta magni in sed laboriosam placeat laborum. Exercitationem fugiat consequatur aut aliquam. Exercitationem a qui provident non. Voluptatem iure impedit maiores ut assumenda. Qui neque ratione maxime.",
    category: "Grocery",
    counter:1,
  },
  {
    id: 50,
    title: "Incredible Concrete Gloves",
    price: "389.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/transport",
    description:
      "Et sunt velit illo laudantium explicabo et omnis veniam. Sed voluptates et dolor saepe omnis sed autem aliquid voluptate. Omnis omnis est non voluptatem ullam maxime libero minus eius.",
    category: "Health",
    counter:1,
  },
  {
    id: 51,
    title: "Gorgeous Fresh Shirt",
    price: "243.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/business",
    description:
      "Perspiciatis omnis quia ipsum neque. Animi blanditiis voluptates. Occaecati sed ut sit quas magni occaecati deleniti enim.",
    category: "Computers",
    counter:1,
  },
  {
    id: 52,
    title: "Refined Granite Tuna",
    price: "252.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/food",
    description:
      "Sequi reiciendis minima cumque deserunt quos tempore eveniet ut. Veniam sint impedit aut accusamus quis sit. Culpa non delectus fugit voluptatum dolorum dolorem ex qui. Non praesentium ab quibusdam impedit qui consequatur culpa molestiae vero. Minus deserunt ipsum consequatur quo iure nisi voluptas optio. Dolores id est id et ut.",
    category: "Tools",
    counter:1,
  },
  {
    id: 53,
    title: "Awesome Concrete Hat",
    price: "655.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/food",
    description:
      "Debitis sit laudantium eum sint. Tempora praesentium sint dignissimos itaque iusto a. Quae autem sequi. Est alias earum aut laboriosam aut et sint.",
    category: "Home",
    counter:1,
  },
  {
    id: 54,
    title: "Sleek Metal Tuna",
    price: "183.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/technics",
    description:
      "Sequi veritatis iusto. Molestiae aliquam maiores voluptatem aperiam fuga. Reprehenderit ipsam ab in necessitatibus. Impedit voluptatem ut. Accusantium eius sequi.",
    category: "Industrial",
    counter:1,
  },
  {
    id: 55,
    title: "Rustic Concrete Tuna",
    price: "739.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/abstract",
    description:
      "Non recusandae harum voluptatum laborum repudiandae beatae illum atque nostrum. Suscipit enim velit fuga. Vel omnis ad hic velit consequatur. Repellat qui blanditiis unde non minima eligendi qui est.",
    category: "Garden",
    counter:1,
  },
  {
    id: 56,
    title: "Rustic Metal Fish",
    price: "896.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/fashion",
    description:
      "Magni minus neque nemo deserunt et porro amet error. Suscipit consequatur qui. Qui consequatur ab eveniet placeat aut. Nostrum voluptatem adipisci. Accusamus aut nesciunt magnam.",
    category: "Computers",
    counter:1,
  },
  {
    id: 57,
    title: "Ergonomic Concrete Tuna",
    price: "293.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Et tenetur qui nulla delectus aliquam sint. Omnis unde odit quisquam assumenda dolorem sit repellendus. Omnis quae molestiae exercitationem. Sit dicta qui. Quae aut voluptatem.",
    category: "Clothing",
    counter:1,
  },
  {
    id: 58,
    title: "Tasty Rubber Chair",
    price: "594.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/abstract",
    description:
      "Distinctio et aliquid. Possimus vel quos aut iusto laborum. Minima voluptas nostrum tenetur debitis quidem. Iure quo neque aut consequuntur doloribus atque. Quasi facere perspiciatis inventore officiis.",
    category: "Clothing",
    counter:1,
  },
  {
    id: 59,
    title: "Tasty Plastic Shirt",
    price: "125.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/sports",
    description:
      "Iusto quod consequatur odit doloribus est quas. Qui at in iusto modi fugit soluta qui. Ex omnis odit iure quo dolorum occaecati quas. Rerum commodi recusandae quia.",
    category: "Jewelery",
    counter:1,
  },
  {
    id: 60,
    title: "Sleek Frozen Computer",
    price: "521.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/people",
    description:
      "Necessitatibus esse molestias reiciendis molestiae error dolorem. Assumenda totam doloremque et sequi ut fuga. Sequi omnis sequi.",
    category: "Tools",
    counter:1,
  },
  {
    id: 61,
    title: "Incredible Metal Sausages",
    price: "374.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/abstract",
    description:
      "Doloremque facere animi cum occaecati magnam mollitia temporibus. Sint sint error et corporis est dignissimos aut perferendis est. Natus ea ipsam mollitia harum sit qui. Eligendi maxime quod.",
    category: "Kids",
    counter:1,
  },
  {
    id: 62,
    title: "Handcrafted Frozen Pants",
    price: "825.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Saepe eius dolores. Omnis voluptatum fugiat impedit dolorem quis veniam nihil ut. Quae dignissimos unde adipisci sit enim dignissimos iste. Voluptatum repellat porro incidunt quidem sunt dolorum officiis. Iure qui voluptate et.",
    category: "Music",
    counter:1,
  },
  {
    id: 63,
    title: "Unbranded Cotton Shoes",
    price: "834.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/food",
    description:
      "Pariatur deserunt architecto. Ex qui qui eius rerum debitis voluptatum similique saepe temporibus. Qui nulla ab voluptatem enim atque dolore doloribus.",
    category: "Baby",
    counter:1,
  },
  {
    id: 64,
    title: "Rustic Fresh Pants",
    price: "438.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/fashion",
    description:
      "Voluptas asperiores perspiciatis est omnis eos aut impedit ea nobis. Vitae est aut. Maiores est debitis illum delectus debitis aut id officia. Quia aut delectus dolorum officia sapiente vel eum consequatur.",
    category: "Grocery",
    counter:1,
  },
  {
    id: 65,
    title: "Fantastic Frozen Shirt",
    price: "855.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Adipisci incidunt voluptatum cupiditate repudiandae et unde et. Fugit doloribus soluta quia quasi et. Et quae quis. Praesentium odio necessitatibus placeat tenetur fugit libero et ducimus.",
    category: "Kids",
    counter:1,
  },
  {
    id: 66,
    title: "Sleek Fresh Car",
    price: "542.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/people",
    description:
      "Aut in minus quam enim deleniti totam qui. Accusantium reprehenderit ut ut aperiam assumenda recusandae eius aut accusamus. Quo et non. Odit nihil rem. Natus fugit adipisci in temporibus et distinctio aliquam.",
    category: "Baby",
    counter:1,
  },
  {
    id: 67,
    title: "Rustic Metal Shirt",
    price: "431.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/sports",
    description:
      "Odit tempora et voluptatem et deserunt harum esse ea aperiam. Saepe vero quam ullam qui cum maxime. Autem sit distinctio cupiditate ab quaerat corrupti quia quia alias. Repellendus minima distinctio impedit dolorum in enim.",
    category: "Toys",
    counter:1,
  },
  {
    id: 68,
    title: "Intelligent Frozen Chips",
    price: "166.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/food",
    description:
      "Sunt ipsam nihil repellendus quos dignissimos voluptas laborum. Eaque aliquam quos est. Reiciendis asperiores quia. Dolorem nesciunt consectetur quia est ut.",
    category: "Kids",
    counter:1,
  },
  {
    id: 69,
    title: "Tasty Steel Keyboard",
    price: "267.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/food",
    description:
      "Et cum quos quis. Temporibus autem corrupti nostrum. Ipsa et ea itaque blanditiis. Et ut nobis. Expedita perspiciatis impedit error eius quia maxime.",
    category: "Computers",
    counter:1,
  },
  {
    id: 70,
    title: "Rustic Cotton Chips",
    price: "630.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/business",
    description:
      "Ea voluptas fugiat quo quaerat. Exercitationem commodi quibusdam ipsum non praesentium voluptatem. Fugit est dignissimos fuga iusto culpa quam dicta. Dolores reprehenderit cumque voluptatem explicabo odit animi rerum voluptatem.",
    category: "Clothing",
    counter:1,
  },
  {
    id: 71,
    title: "Licensed Metal Shoes",
    price: "625.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/nature",
    description:
      "Magnam voluptatem eum quam. Id perspiciatis et voluptas nostrum cum tenetur aut. Laboriosam quo ea et qui voluptatem quae enim voluptatem autem. Est exercitationem molestiae et omnis est molestias. Officia harum ea aut sapiente repellat similique at non. Reprehenderit quis at et recusandae.",
    category: "Grocery",
    counter:1,
  },
  {
    id: 72,
    title: "Small Rubber Tuna",
    price: "102.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/city",
    description:
      "Voluptatum adipisci facere ipsam id minima blanditiis. Non occaecati sapiente eum in vel. Error quia tempora voluptatem. Perspiciatis sed nihil enim magni inventore temporibus eum et.",
    category: "Beauty",
    counter:1,
  },
  {
    id: 73,
    title: "Gorgeous Plastic Tuna",
    price: "391.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/technics",
    description:
      "Ea eos id in. Ad et vitae cumque. Ducimus minima asperiores non distinctio veritatis dolores ducimus nam in. Suscipit minima quos reiciendis. Voluptatem sint quas aut eum consequuntur. Dolorum voluptate facere.",
    category: "Outdoors",
    counter:1,
  },
  {
    id: 74,
    title: "Awesome Granite Bike",
    price: "452.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/sports",
    description:
      "Vel quae et laborum error ullam nesciunt. Tenetur quo ut rerum. Voluptas harum qui rerum a neque. Quia molestias et velit facilis omnis. Ipsa eos totam deleniti voluptas occaecati vel est beatae ad.",
    category: "Tools",
    counter:1,
  },
  {
    id: 75,
    title: "Incredible Metal Gloves",
    price: "845.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/technics",
    description:
      "Hic possimus quae saepe libero molestiae. Rerum ipsa sit quam et laboriosam labore dolores. Nostrum in quam facilis omnis reiciendis officiis nihil nam aut.",
    category: "Outdoors",
    counter:1,
  },
  {
    id: 76,
    title: "Awesome Steel Mouse",
    price: "401.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/people",
    description:
      "Vel sint velit. Nihil quia non nobis est at iusto. Et cumque nemo sunt provident nostrum molestias et. Quae non voluptas et et eos est fugit veritatis.",
    category: "Kids",
    counter:1,
  },
  {
    id: 77,
    title: "Licensed Cotton Cheese",
    price: "743.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/nightlife",
    description:
      "Natus placeat dignissimos dolore accusamus facere est. Praesentium sed dignissimos officia consequatur rerum molestias ab. Est voluptates placeat. Vel officiis cum corrupti culpa recusandae repellendus aspernatur et. Nemo pariatur minus neque sunt expedita aut quo.",
    category: "Health",
    counter:1,
  },
  {
    id: 78,
    title: "Tasty Metal Keyboard",
    price: "744.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Consequuntur enim quo quos. Sunt sit eveniet. Est dolorum in ab fugit. Quaerat adipisci incidunt commodi iusto dolor ad non.",
    category: "Baby",
    counter:1,
  },
  {
    id: 79,
    title: "Small Cotton Fish",
    price: "960.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/sports",
    description:
      "Quo inventore voluptas qui eaque eum quidem. Non dolor reprehenderit labore quae possimus. Eaque et quod minima. Est commodi omnis labore sunt eum vel placeat quam. Amet unde voluptates impedit velit similique sint.",
    category: "Health",
    counter:1,
  },
  {
    id: 80,
    title: "Tasty Cotton Pizza",
    price: "700.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/sports",
    description:
      "Aut aspernatur aut velit. Similique dignissimos aut laboriosam. Fugit necessitatibus accusantium quis. Quaerat quod officia autem autem aut officiis. Eum eum qui aspernatur ipsa. Debitis recusandae nam vel aspernatur.",
    category: "Toys",
    counter:1,
  },
  {
    id: 81,
    title: "Generic Wooden Pizza",
    price: "562.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/nature",
    description:
      "Et et ipsam eum accusamus. Et consequuntur laudantium nobis omnis fugit architecto quaerat ad. Doloremque tempora rerum rem rem eveniet. Velit quas id perferendis tempora vero maiores ipsa quisquam.",
    category: "Beauty",
    counter:1,
  },
  {
    id: 82,
    title: "Sleek Wooden Car",
    price: "216.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/nightlife",
    description:
      "Molestiae vitae molestias eligendi consequatur tenetur autem. Eligendi est et nihil. Voluptate tempora aliquam quia. Qui aspernatur in. Possimus deserunt reprehenderit consequatur sint soluta sed quos eaque eius. Vel qui reprehenderit perferendis aut.",
    category: "Tools",
    counter:1,
  },
  {
    id: 83,
    title: "Gorgeous Fresh Pants",
    price: "710.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/nightlife",
    description:
      "Officiis voluptatem officiis molestias eius est officia reprehenderit autem quasi. Totam et non enim. Reprehenderit et dolor et porro.",
    category: "Games",
    counter:1,
  },
  {
    id: 84,
    title: "Rustic Metal Tuna",
    price: "116.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/abstract",
    description:
      "Sint qui repudiandae est quam non assumenda qui incidunt. Sint exercitationem expedita qui provident velit est. Nam laudantium consequatur voluptatibus.",
    category: "Home",
    counter:1,
  },
  {
    id: 85,
    title: "Licensed Metal Salad",
    price: "542.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/technics",
    description:
      "Maxime corrupti omnis commodi et in culpa ut rerum. Sint illo eos optio et explicabo. Expedita autem voluptatibus dolores beatae.",
    category: "Grocery",
    counter:1,
  },
  {
    id: 86,
    title: "Tasty Concrete Ball",
    price: "426.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/abstract",
    description:
      "Repellendus pariatur atque. Eum voluptas quis id atque dicta ullam minus. Et eos adipisci at exercitationem cumque qui impedit voluptas. Aut aut et nihil ad sed amet rerum non. Est sed quisquam eum in et in quo. Non fuga quo labore numquam.",
    category: "Clothing",
    counter:1,
  },
  {
    id: 87,
    title: "Small Concrete Salad",
    price: "723.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Facilis fugit sit. Illo qui in maxime. Delectus laboriosam molestiae voluptatem ea qui mollitia. Eligendi sunt eligendi qui vitae fuga ab ea delectus. Cum sed autem eligendi.",
    category: "Beauty",
    counter:1,
  },
  {
    id: 88,
    title: "Small Fresh Car",
    price: "210.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/city",
    description:
      "Aliquam et molestiae qui. Expedita aliquam ipsa quaerat quaerat aut est veritatis sint. Quisquam voluptatibus soluta sit quia consequatur quia. Rerum ut et.",
    category: "Clothing",
    counter:1,
  },
  {
    id: 89,
    title: "Incredible Metal Bacon",
    price: "77.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/people",
    description:
      "At qui nostrum temporibus aperiam consequatur recusandae. Fugiat natus est consequatur. Placeat ex nam architecto porro et molestiae iusto eos. Omnis dolores tempore sit.",
    category: "Jewelery",
    counter:1,
  },
  {
    id: 90,
    title: "Sleek Metal Cheese",
    price: "529.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/nightlife",
    description:
      "Error veritatis numquam possimus ut praesentium enim qui provident suscipit. Ut quidem aut dicta rerum. Iste quidem rem consequatur architecto ipsam sint molestias expedita tenetur. Qui similique aliquid. At atque iste illum est accusantium maxime minus perferendis similique.",
    category: "Industrial",
    counter:1,
  },
  {
    id: 91,
    title: "Refined Plastic Fish",
    price: "141.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/abstract",
    description:
      "Earum doloribus cupiditate fugiat qui ut earum. Non quam minus adipisci officia unde rem ut. Et perspiciatis autem nihil aut numquam sunt. Nihil quia ut consequatur voluptatum laborum ipsa sint tenetur. Porro quia earum sed qui id quos facilis magnam.",
    category: "Books",
    counter:1,
  },
  {
    id: 92,
    title: "Fantastic Plastic Fish",
    price: "205.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/fashion",
    description:
      "Natus ea aliquid. Qui perferendis numquam cupiditate omnis accusantium officia. Totam distinctio sunt natus exercitationem rem possimus id.",
    category: "Industrial",
    counter:1,
  },
  {
    id: 93,
    title: "Licensed Wooden Mouse",
    price: "678.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/animals",
    description:
      "Dignissimos et ut aut optio labore at laborum nam. Dolores ducimus possimus et minus. Eius sint aspernatur dolorum sit libero ea omnis nulla.",
    category: "Beauty",
    counter:1,
  },
  {
    id: 94,
    title: "Small Frozen Salad",
    price: "495.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/city",
    description:
      "Vitae nam qui. Accusantium ea dolore assumenda est vitae animi expedita voluptatum rerum. Dignissimos cupiditate officiis sit ut a sequi ad voluptatem consequatur. Et soluta veniam. Eum dolorem magni aliquid incidunt unde labore autem mollitia culpa.",
    category: "Games",
    counter:1,
  },
  {
    id: 95,
    title: "Awesome Soft Car",
    price: "943.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/cats",
    description:
      "Quibusdam incidunt autem dolor ullam labore quis. Laborum occaecati animi ex error. Eos molestias perspiciatis ut perferendis quod minus cumque veniam.",
    category: "Shoes",
    counter:1,
  },
  {
    id: 96,
    title: "Small Wooden Mouse",
    price: "777.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/sports",
    description:
      "Quisquam eligendi natus officia ut doloremque. Qui excepturi inventore vel incidunt dolor earum est rerum. Minus quas commodi eius consequatur. Nulla vel vitae eius velit sint sit recusandae nisi.",
    category: "Clothing",
    counter:1,
  },
  {
    id: 97,
    title: "Licensed Fresh Computer",
    price: "181.00",
    special: true,
    imageUrl: "http://lorempixel.com/640/480/sports",
    description:
      "Temporibus sit sed. Aut quidem quos mollitia. At omnis odit porro velit voluptatem quasi at. Possimus sit dolorem. Id mollitia iste error ut ullam omnis omnis officia. Placeat necessitatibus accusantium voluptatem at voluptas vel sit quia.",
    category: "Tools",
    counter:1,
  },
  {
    id: 98,
    title: "Awesome Wooden Soap",
    price: "556.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/fashion",
    description:
      "Explicabo repellat commodi ipsam est magnam nihil repudiandae dolor quia. Ea eum ut consequuntur sapiente eveniet voluptates eaque dolor. Quo cupiditate exercitationem. Dignissimos maxime quas veniam laborum ea sed.",
    category: "Industrial",
    counter:1,
  },
  {
    id: 99,
    title: "Generic Steel Mouse",
    price: "963.00",
    special: false,
    imageUrl: "http://lorempixel.com/640/480/fashion",
    description:
      "Nihil quo quis doloribus velit sunt culpa enim. Itaque qui facilis incidunt maxime et voluptas fugiat. Aut provident molestias aperiam doloremque quis iste possimus perferendis sed.",
    category: "Industrial",
    counter:1,
  },
];
